name:                stochastic-hybrid-sim
version:             0.1.0.0
github:              "cplaursen/stochastic-hybrid-sim"
license:             BSD3
author:              "Christian Pardillo Laursen"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"
language:            "GHC2021"

extra-source-files:
  - README.md
  - ChangeLog.md
  - src/parser/Parser.y
  - src/parser/Lexer.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stochastic-hybrid-sim#readme>

dependencies:
  - base
  - vector
  - linear
  - mwc-random
  - mtl
  - array
  - unordered-containers
  - containers
  - primitive
  - microlens-platform
  - syb
  - monad-parallel

  # Command line options
  - optparse-applicative


library: 
  source-dirs: 
    - src
    - src/parser
  build-tools:
    - alex
    - happy

executables:
  stochastic-hybrid-sim:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - stochastic-hybrid-sim

tests:
  stochastic-hybrid-sim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stochastic-hybrid-sim
